name: Docker Build and Push

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKER_CLI_AGGREGATE: 1
      DOCKER_BUILDKIT: 1

    strategy:
      matrix:
        maven_version:
          - 3.9.6

    steps:
      - name: Checkout code

        uses: actions/checkout@v4
      - name: Set up Docker Buildx

        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1

        with:
          username: ${{ vars.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build and push Docker image
        run: |
          docker buildx create --use
          docker buildx build \
            -t ${{ vars.DOCKER_HUB_USERNAME }}/ci-builder-maven:latest \
            -t ${{ vars.DOCKER_HUB_USERNAME }}/ci-builder-maven:${{ matrix.maven_version }} \
            -t ${{ vars.DOCKER_HUB_USERNAME }}/ci-builder-maven:${{ matrix.maven_version }}-${{ github.run_number }} \
            --build-arg MAVEN_VERSION=${{ matrix.maven_version }} \
            --push .
